import { useState } from "react"
import Modal from "../components/Modal"
import Button from "../components/Button"

const ModalPage = () => {
    const [showModal, setShowModal] = useState(false)

    const handleClick = () => {
        setShowModal(true)
    }

    const handleClose = () => {
        setShowModal(false)
    }

    const actionBar = <div>
        <Button onClick={handleClose} primary>I accept</Button>
    </div>

    const modal = (<Modal onClose={handleClose} actionBar={actionBar}>
            <p>Do you agree?</p>
        </Modal>)

    return (
        <div className="relative">
            <Button primary onClick={handleClick}>Open Modal</Button> 
            {showModal && modal}
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo ipsum, bibendum ac massa sed, pretium facilisis sapien. Duis ultrices imperdiet enim sed molestie. Fusce gravida volutpat quam, ac sollicitudin velit cursus quis. Etiam maximus, neque quis pellentesque scelerisque, sapien quam cursus leo, sit amet laoreet eros arcu non quam. Praesent nisl libero, condimentum eget tincidunt eget, bibendum quis diam. Morbi quis quam tempus, efficitur leo nec, luctus nulla. Ut tempor sem risus, eu euismod turpis finibus ac. Nulla facilisi. Phasellus pulvinar venenatis libero ac bibendum. Mauris interdum nunc pharetra mi ultricies molestie. Praesent et augue at dolor ullamcorper vehicula eu ut mauris. Morbi et leo enim. Aenean pharetra commodo eros, a volutpat nisi congue sit amet. Ut lobortis, lacus eu gravida lacinia, quam dui tincidunt urna, a dignissim dolor velit tempus dui.</p>
        </div>
    )
}

export default ModalPage